#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<long long> a)
{
    sort(a.begin(), a.end(), greater<long long>());
    long long bob = 0;
    long long alice = 0;
    bool is_alice_turn = true;
    for (long long i = 0; i < N; i++)
    {
        if (is_alice_turn)
        {
            alice += a[i];
        }
        else
        {
            bob += a[i];
        }

        is_alice_turn = !is_alice_turn;
    }
    cout << alice - bob << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    // N = 3;
    std::vector<long long> a(N);
    // a.push_back(2);
    // a.push_back(7);
    // a.push_back(4);
    // a.push_back(1);
    // a.push_back(3);
    for (int i = 0; i < N; i++)
    {
        scanf("%lld", &a[i]);
    }
    solve(N, std::move(a));
    return 0;
}
